"""Validate complete language packs and compile them to a synchronous catalog.
Run after editing lib/l10n/*.json. No network or translation service is used.
"""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parents[1]
packs = {p.stem: json.loads(p.read_text()) for p in sorted((root / 'lib/l10n').glob('*.json'))}
assert set(packs) == {'ms', 'en', 'id', 'zh', 'ta', 'ar'}
base = packs['ms']
for code, pack in packs.items():
    assert pack.keys() == base.keys(), f'{code}: missing/extra keys'
    for key, value in pack.items():
        assert value.strip(), f'{code}.{key}: empty'
        assert set(re.findall(r'\{\w+\}', value)) == set(re.findall(r'\{\w+\}', base[key])), f'{code}.{key}: placeholders'
encoded = json.dumps(packs, ensure_ascii=False, indent=2).replace('$', r'\$')
(root / 'lib/l10n/messages.dart').write_text('// Generated by scripts/generate_localizations.py. Do not edit.\nconst messages = <String, Map<String, String>>' + encoded + ';\n')
print(f'{len(packs)} complete languages, {len(base)} keys each')
